version: '3'
services:
  sandbox-postgres:
    image: 'postgres:13.1'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cinemaDBS
