name: CI
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
jobs:
  all-cli-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16.2'
      - run: yarn install
      - run: yarn build
      - run: yarn lint
      - run: yarn check-format
      - run: yarn check-types
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16.2'
      - uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn serve
